# Generated by Django 2.2.3 on 2019-07-30 07:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bauthor', models.CharField(default='', max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcategory', models.CharField(default='', max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='myblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(default='', max_length=55)),
                ('bdate', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 30, 7, 11, 35, 944061, tzinfo=utc), null=True)),
                ('bdiscription', models.CharField(default='', max_length=255)),
                ('bcategory', models.CharField(default='', max_length=55)),
                ('bimage', models.ImageField(upload_to='static/images')),
                ('bauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.auther')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcomment', models.CharField(default='', max_length=10000)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.myblog')),
            ],
        ),
        migrations.CreateModel(
            name='categoryblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.myblog')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.category')),
            ],
        ),
    ]
