# Generated by Django 2.2.3 on 2019-07-30 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190730_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='bcategory',
        ),
        migrations.AlterField(
            model_name='myblog',
            name='bdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 30, 10, 27, 34, 141092, tzinfo=utc), null=True),
        ),
    ]
