# Generated by Django 2.2.3 on 2019-07-30 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190730_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myblog',
            old_name='bauthor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='myblog',
            name='bdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 30, 10, 50, 13, 873043, tzinfo=utc), null=True),
        ),
    ]
