# Generated by Django 2.2.3 on 2019-07-30 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20190730_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='bdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 30, 11, 23, 17, 580957, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='bdiscription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
